import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

import 'screens/login_screen.dart';
import 'screens/home_screen.dart';
import 'screens/profile_screen.dart';
import 'screens/about_screen.dart';
import 'screens/map_screen.dart';
import 'screens/cabin_screen.dart';
import 'screens/timetable_screen.dart';
import 'screens/next_lecture_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print('Firebase initialized successfully!');
  } catch (e) {
    print('Firebase already initialized: $e');
  }

  runApp(const SmartFacultyApp());
}

class SmartFacultyApp extends StatelessWidget {
  const SmartFacultyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Smart Faculty',

      // ─── Light Theme ───────────────────────────────────────────
      theme: ThemeData(
        brightness: Brightness.light,
        scaffoldBackgroundColor: Colors.white,
        fontFamily: 'sans-serif',
        colorScheme: ColorScheme.light(
          primary: const Color(0xFF1A1A1A),
          secondary: const Color(0xFFF1F3F5),
          surface: Colors.white,
          onPrimary: Colors.white,
          onSecondary: const Color(0xFF1A1A1A),
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          elevation: 0,
          iconTheme: IconThemeData(color: Color(0xFF1A1A1A)),
          titleTextStyle: TextStyle(
            color: Color(0xFF1A1A1A),
            fontSize: 32,
            fontWeight: FontWeight.bold,
          ),
        ),
        switchTheme: SwitchThemeData(
          thumbColor: WidgetStateProperty.resolveWith((states) {
            if (states.contains(WidgetState.selected)) {
              return const Color(0xFFB0B0C0);
            }
            return Colors.white;
          }),
          trackColor: WidgetStateProperty.resolveWith((states) {
            if (states.contains(WidgetState.selected)) {
              return const Color(0xFF1A1A1A);
            }
            return const Color(0xFFB0B0C0);
          }),
        ),
        bottomNavigationBarTheme: const BottomNavigationBarThemeData(
          backgroundColor: Colors.white,
          selectedItemColor: Color(0xFF1A1A1A),
          unselectedItemColor: Colors.grey,
          type: BottomNavigationBarType.fixed,
          showSelectedLabels: true,
          showUnselectedLabels: true,
          elevation: 8,
        ),
      ),

      // ─── Dark Theme ────────────────────────────────────────────
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF121212),
        fontFamily: 'sans-serif',
        colorScheme: ColorScheme.dark(
          primary: const Color(0xFFE0E0E0),
          secondary: const Color(0xFF2C2C2C),
          surface: const Color(0xFF1E1E1E),
          onPrimary: const Color(0xFF121212),
          onSecondary: const Color(0xFFE0E0E0),
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF121212),
          elevation: 0,
          iconTheme: IconThemeData(color: Color(0xFFE0E0E0)),
          titleTextStyle: TextStyle(
            color: Color(0xFFE0E0E0),
            fontSize: 32,
            fontWeight: FontWeight.bold,
          ),
        ),
        switchTheme: SwitchThemeData(
          thumbColor: WidgetStateProperty.resolveWith((states) {
            if (states.contains(WidgetState.selected)) {
              return const Color(0xFFB0B0C0);
            }
            return Colors.grey;
          }),
          trackColor: WidgetStateProperty.resolveWith((states) {
            if (states.contains(WidgetState.selected)) {
              return const Color(0xFFE0E0E0);
            }
            return const Color(0xFF444444);
          }),
        ),
        bottomNavigationBarTheme: const BottomNavigationBarThemeData(
          backgroundColor: Color(0xFF1E1E1E),
          selectedItemColor: Color(0xFFE0E0E0),
          unselectedItemColor: Colors.grey,
          type: BottomNavigationBarType.fixed,
          showSelectedLabels: true,
          showUnselectedLabels: true,
          elevation: 8,
        ),
      ),

      themeMode: ThemeMode.system, // Follows device setting
      // ─── Auth Gate ─────────────────────────────────────────────
      home: const AuthWrapper(),

      // ─── Named Routes ──────────────────────────────────────────
      routes: {
        '/login': (context) => const LoginScreen(),
        '/home': (context) => const HomeScreen(),
        '/profile': (context) => const ProfileScreen(),
        '/about': (context) => const AboutScreen(),
        '/map': (context) => const FacultyMapScreen(),
        '/cabin': (context) => const CabinScreen(),
        '/timetable': (context) => const TimeTableScreen(),
        '/next_lecture': (context) => const NextLectureScreen(),
      },
    );
  }
}

// ─── Auth Wrapper ─────────────────────────────────────────────────
// Automatically sends user to Home if already logged in,
// otherwise sends to Login screen
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // Debug prints
        print('=== AuthWrapper ===');
        print('ConnectionState: ${snapshot.connectionState}');
        print('HasData: ${snapshot.hasData}');
        print('User: ${snapshot.data?.email}');
        print('HasError: ${snapshot.hasError}');

        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        if (snapshot.hasError) {
          return const Scaffold(
            body: Center(child: Text('Something went wrong')),
          );
        }
        if (snapshot.hasData && snapshot.data != null) {
          return const HomeScreen();
        }
        return const LoginScreen();
      },
    );
  }
}
